# Generated by Django 4.2.7 on 2023-11-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Yıl'),
        ),
    ]
