# Generated by Django 4.2.7 on 2023-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0003_reports_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Sıra'),
            preserve_default=False,
        ),
    ]
