# Generated by Django 4.2.7 on 2023-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0004_projects_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='editions',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
    ]
