# Generated by Django 4.2.7 on 2023-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0005_alter_editions_created_by_alter_editions_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editions',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AddField(
            model_name='reports',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
    ]
