# Generated by Django 4.2.7 on 2023-12-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_images_created_by_alter_images_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
    ]
