# Generated by Django 4.2.7 on 2023-12-08 20:46

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen')),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen')),
                ('order', models.SmallIntegerField(verbose_name='Sıra')),
                ('file', models.FileField(upload_to='announcements/file', verbose_name='Dosya')),
                ('name', models.CharField(max_length=300, verbose_name='İsim')),
                ('image', models.ImageField(upload_to='announcements/img', verbose_name='Resim')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Yayınlansın mı?')),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnouncementsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Metin')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Başlık')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='announcements.announcements')),
            ],
            options={
                'verbose_name': 'announcements Translation',
                'db_table': 'announcements_announcements_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
