# Generated by Django 4.2.7 on 2023-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='url',
        ),
        migrations.AddField(
            model_name='mainslidertranslation',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Yazısı'),
        ),
        migrations.AddField(
            model_name='mainslidertranslation',
            name='button_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
