# Generated by Django 4.2.7 on 2023-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_newstranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Başlık'),
        ),
    ]
