# Generated by Django 4.2.7 on 2023-11-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mediagallery_mediagallerytranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediagallerytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mediagallerytranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MediaGallery',
        ),
        migrations.DeleteModel(
            name='MediaGalleryTranslation',
        ),
    ]
