# Generated by Django 4.2.7 on 2023-11-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mediagallerytranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AlterUniqueTogether(
            name='newstranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='newstranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsTranslation',
        ),
    ]
