# Generated by Django 4.2.7 on 2023-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_images_alter_newstranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('message', models.CharField(max_length=3000, verbose_name='Mesaj')),
            ],
            options={
                'verbose_name_plural': 'İletişim',
            },
        ),
    ]
