# Generated by Django 4.2.7 on 2023-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pages_pagestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
    ]
