# Generated by Django 4.2.7 on 2023-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mainslider_is_publish_alter_mainslider_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
    ]
