# Generated by Django 4.2.7 on 2023-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pages_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='banner_img',
            field=models.FileField(blank=True, null=True, upload_to='img/pages', verbose_name='Banner Resmi'),
        ),
    ]
