# Generated by Django 4.2.7 on 2023-12-09 12:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pages_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestranslation',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Metin'),
        ),
    ]
