# Generated by Django 4.2.7 on 2023-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_pagestranslation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme'),
        ),
    ]
