# Generated by Django 4.2.7 on 2023-11-06 18:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='İsim')),
            ],
            options={
                'verbose_name_plural': 'Menü Konumları',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('logo', models.FileField(upload_to='img/site_settings', verbose_name='Logo')),
                ('shortcut', models.FileField(upload_to='img/site_settings', verbose_name='İkon')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.CharField(max_length=100, verbose_name='Mail')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('google_maps_link', models.CharField(max_length=1000, verbose_name='Google Maps Link')),
            ],
            options={
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='Whatsapp')),
            ],
            options={
                'verbose_name_plural': 'Sosyal Medya Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.SmallIntegerField(blank=True, null=True, verbose_name='Sıralama')),
                ('target_blank', models.BooleanField(default=False, verbose_name='Yeni sayfada açılsın mı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu_location', models.ForeignKey(blank=True, default='Footer', null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.menulocation', verbose_name='Menü Tipi')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_settings.menu', verbose_name='Üst Menü')),
            ],
            options={
                'verbose_name_plural': 'Menüler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=250, verbose_name='Başlık')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site_settings.menu')),
            ],
            options={
                'verbose_name': 'menu Translation',
                'db_table': 'site_settings_menu_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
