# Generated by Django 4.2.7 on 2023-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Ekeleyen'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Güncelleyen'),
        ),
    ]
