# Generated by Django 4.2.7 on 2023-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme'),
        ),
    ]
